#!/bin/bash
# The host's own utility shaders (src/host/shaders/*.comp, and the graphics
# stages listed below), compiled offline into checked-in headers of SPIR-V
# words, so the build needs no shader compiler. Run after editing a shader;
# needs glslc and spirv-val.
#   tools/build_shaders.sh [src/host/shaders/<file> ...]   (all of them by default)
# A compute shader name.comp becomes name.spv.h (k_name_spv); a graphics
# stage name.vert / name.frag becomes name_vert.spv.h / name_frag.spv.h
# (k_name_vert_spv, k_name_frag_spv). The presenter's and the overlay's stages
# are not here: host/present_spv.h and host/overlay.cpp carry their own words.
set -eu
cd "$(dirname "$0")/.."
graphics="src/host/shaders/stream_selftest.vert src/host/shaders/stream_selftest.frag"
if [ $# -gt 0 ]; then
    sources="$*"
else
    sources="$(ls src/host/shaders/*.comp) $graphics"
fi
for src in $sources; do
    file=$(basename "$src")
    case "$file" in
        *.comp) name=${file%.comp} ;;
        *.vert) name=${file%.vert}_vert ;;
        *.frag) name=${file%.frag}_frag ;;
        *) echo "$src: not a .comp, .vert or .frag" >&2; exit 1 ;;
    esac
    out=src/host/shaders/$name.spv.h
    tmp=$(mktemp)
    glslc -O --target-env=vulkan1.2 -o "$tmp.spv" "$src"
    spirv-val --target-env vulkan1.2 "$tmp.spv"
    glslc -O --target-env=vulkan1.2 -mfmt=num -o "$tmp" "$src"
    {
        echo "// Generated by tools/build_shaders.sh from $file - do not edit."
        echo "#pragma once"
        echo "#include <cstdint>"
        echo "inline constexpr std::uint32_t k_${name}_spv[] = {"
        cat "$tmp"
        echo "};"
    } > "$out"
    rm -f "$tmp" "$tmp.spv"
    echo "$out: $(grep -o '0x' "$out" | wc -l) words"
done
